### PR TITLE
fix sourcemap support

### PR DESCRIPTION
**Pull request by billowz**
- Upgrade rollup to 1.0.0
- Added mapContent option
- Added sourcemap test case
- Fix source path in the sourcemap

### CODE REVIEW

**Comment by aMarCruz** [comment]
@tao-zeng , I think it's better to put the `mapContent` option in a separate PR. Although I do not really think it's useful, as far as I know Rollup ignores the content put there by the plugins. Do you have any use case?

and good catch with "rm -rf" :+1:   ...I forgot Windows exists

**Comment by tao-zeng** [comment]
@aMarCruz Rollup1.x does not generate  source content when the plugin's sourcemap does not contain source content

### my test case
index.ts
```JS
//#if _DEBUG
export const a = 1
/*#else
export const a = 1
//#endif */
```
rollup config
```JS
export default {
  input: 'index.ts',
  output: {
     name: 'test',
     format: 'umd',
     file: 'bundle.js',
     sourcemap: true,
     amd: {id: 'test'}
  },
  plugins: [
    nodeResolve({ jsnext: true, extensions: ['*.ts'] }),
    commonjs(),
    babel({extensions: ['*.ts'] }),
    jscc({ values: { _DEBUG: true } })
  ]
}
```
bundle.js.map
```JS
{"version":3,"file":"bundle.js","sources":["./src/src/index.ts"],"sourcesContent":[null],"names":["a"],"mappings":";;;;;;;;;;;;;;;AAAA;;;;;;;;;;;;;;AAeA,MAAaA,CAAC,GAAG,CAAV;;;;"}
```
1. sourcesContent is [null]
2. sources expect ["./src/index.ts"]

**Comment by tao-zeng** [comment]
@aMarCruz The mapContent option is a better idea to work with the sourceupExcludeSources option of the rollup

**Comment by aMarCruz** [comment]
@tao-zeng I will check it asap. Thanks.

**Comment by billowz** [comment]
@aMarCruz  I have rewritten the sourcemap fix code
1. Upgrade rollup to 1.0.0
2. Added mapContent option
3. Add sourcemap test case

**The source path is incorrect for the following reasons:**

The source path in the sourcemap returned by jscc is the path relative to process.pwd(), rollup will resolve source path through the file's directory absolute path and the source path in the returned source map by the plugin

```JS
const sources = originalSourcemap.sources;
const sourcesContent = originalSourcemap.sourcesContent || [];

if (sources == null || (sources.length <= 1 && sources[0] == null)) {
	source = new Source(module.id, sourcesContent[0]);
	sourcemapChain = [originalSourcemap as RawSourceMap].concat(sourcemapChain);
} else {
	// TODO indiscriminately treating IDs and sources as normal paths is probably bad.
	const directory = dirname(module.id) || '.';
	const sourceRoot = originalSourcemap.sourceRoot || '.';
        
        // parse the source path in sourcemap
	const baseSources = sources.map(
		(source, i) => new Source(resolve(directory, sourceRoot, source), sourcesContent[i])
	);
	
	source = new Link(originalSourcemap as any, baseSources) as any;
}
```

See the rollup source: https://github.com/rollup/rollup/blob/v1.15.6/src/utils/collapseSourcemaps.ts#L196


I hope that you can check and merge the RP, Thanks.

**Comment by atompkins** [comment]
What is the status on this please?

**Comment by aMarCruz** [comment]
@atompkins , merged, I will publish a new version this week.
@billowz thanks and I apologize for the long delay.

**Pull request merged**
